package service

import (
	"context"
	"errors"

	"core/internal/model"
	"core/internal/repository"
)

// Sentinel errors returned by CommunityService so handlers can map them to
// HTTP status codes.
var (
	ErrCommunityNotFound = errors.New("community not found")
	ErrCommunityExists   = errors.New("community already exists")
	ErrParentNotFound    = errors.New("parent community not found")
	ErrCycle             = errors.New("parent would create a cycle")
	ErrHasChildren       = errors.New("community has children")
)

// CommunityService provides business logic for community operations.
type CommunityService struct {
	repo *repository.CommunityRepository
}

// NewCommunityService creates a new CommunityService.
func NewCommunityService(repo *repository.CommunityRepository) *CommunityService {
	return &CommunityService{repo: repo}
}

// List returns all communities with their computed levels.
func (s *CommunityService) List(ctx context.Context) (*model.CommunitiesListResponse, error) {
	communities, err := s.repo.List(ctx)
	if err != nil {
		return nil, err
	}
	s.applyLevels(communities)
	return &model.CommunitiesListResponse{Communities: communities}, nil
}

// Get returns a single community with its computed level.
func (s *CommunityService) Get(ctx context.Context, id string) (*model.Community, error) {
	comm, err := s.repo.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if comm == nil {
		return nil, nil
	}
	all, err := s.repo.List(ctx)
	if err != nil {
		return nil, err
	}
	level := computeLevel(comm.ID, comm.ParentID, all)
	comm.Level = level
	return comm, nil
}

// GetTree returns the communities assembled as a tree with computed levels.
func (s *CommunityService) GetTree(ctx context.Context) ([]model.HierarchicalCommunity, error) {
	communities, err := s.repo.List(ctx)
	if err != nil {
		return nil, err
	}
	s.applyLevels(communities)
	return buildTree(communities), nil
}

// Create creates a new community, validating that the parent (if any) exists.
//
// If req.ID is empty a UUID is generated by the repository; the service
// then re-reads the community using the returned identifier.
func (s *CommunityService) Create(ctx context.Context, req model.CommunityCreateRequest) (*model.Community, error) {
	if req.ID != "" {
		exists, err := s.repo.Exists(ctx, req.ID)
		if err != nil {
			return nil, err
		}
		if exists {
			return nil, ErrCommunityExists
		}
	}
	if req.ParentID != nil {
		parentExists, err := s.repo.Exists(ctx, *req.ParentID)
		if err != nil {
			return nil, err
		}
		if !parentExists {
			return nil, ErrParentNotFound
		}
	}
	id, err := s.repo.Create(ctx, req)
	if err != nil {
		return nil, err
	}
	return s.Get(ctx, id)
}

// Update updates an existing community, validating the new parent and rejecting
// moves that would create a cycle.
func (s *CommunityService) Update(ctx context.Context, id string, req model.CommunityUpdateRequest) (*model.Community, error) {
	exists, err := s.repo.Exists(ctx, id)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, nil
	}
	if req.ParentID != nil {
		if *req.ParentID == id {
			return nil, ErrCycle
		}
		parentExists, err := s.repo.Exists(ctx, *req.ParentID)
		if err != nil {
			return nil, err
		}
		if !parentExists {
			return nil, ErrParentNotFound
		}
		all, err := s.repo.List(ctx)
		if err != nil {
			return nil, err
		}
		if wouldCreateCycle(id, *req.ParentID, all) {
			return nil, ErrCycle
		}
	}
	comm, err := s.repo.Update(ctx, id, req)
	if err != nil {
		return nil, err
	}
	if comm == nil {
		return nil, nil
	}
	// Refresh level since parent_id may have changed.
	level, err := s.levelOf(ctx, id)
	if err != nil {
		return nil, err
	}
	comm.Level = level
	return comm, nil
}

// Delete removes a community. It refuses to delete a community that still has
// children; callers should delete or re-parent the children first.
func (s *CommunityService) Delete(ctx context.Context, id string) error {
	exists, err := s.repo.Exists(ctx, id)
	if err != nil {
		return err
	}
	if !exists {
		return ErrCommunityNotFound
	}
	hasChildren, err := s.repo.HasChildren(ctx, id)
	if err != nil {
		return err
	}
	if hasChildren {
		return ErrHasChildren
	}
	_, err = s.repo.Delete(ctx, id)
	return err
}

// levelOf returns the level of a single community by listing all communities
// and walking the parent chain.
func (s *CommunityService) levelOf(ctx context.Context, id string) (int, error) {
	comm, err := s.repo.Get(ctx, id)
	if err != nil {
		return 0, err
	}
	if comm == nil {
		return 0, nil
	}
	all, err := s.repo.List(ctx)
	if err != nil {
		return 0, err
	}
	return computeLevel(comm.ID, comm.ParentID, all), nil
}

// applyLevels populates the Level field on every community in place.
func (s *CommunityService) applyLevels(communities []model.Community) {
	levels := make(map[string]int, len(communities))
	for _, c := range communities {
		levels[c.ID] = computeLevel(c.ID, c.ParentID, communities)
	}
	for i := range communities {
		communities[i].Level = levels[communities[i].ID]
	}
}

// computeLevel returns the level of a community by walking its parent chain.
// A root (no parent) is level 1; a child of a level-N community is level N+1.
// If the chain is broken (parent_id points to a missing community), the
// community is treated as a root at level 1.
func computeLevel(_ string, parentID *string, all []model.Community) int {
	const maxDepth = 64
	byID := make(map[string]model.Community, len(all))
	for _, c := range all {
		byID[c.ID] = c
	}
	level := 1
	current := parentID
	depth := 0
	for current != nil {
		if depth >= maxDepth {
			return level
		}
		parent, ok := byID[*current]
		if !ok {
			return level
		}
		level++
		current = parent.ParentID
		depth++
	}
	return level
}

// wouldCreateCycle returns true if setting self's parent to newParent would
// create a cycle, i.e. newParent (or any of its ancestors) is self.
func wouldCreateCycle(selfID, newParentID string, all []model.Community) bool {
	byID := make(map[string]model.Community, len(all))
	for _, c := range all {
		byID[c.ID] = c
	}
	current := newParentID
	const maxDepth = 64
	for i := 0; i < maxDepth; i++ {
		if current == selfID {
			return true
		}
		c, ok := byID[current]
		if !ok || c.ParentID == nil {
			return false
		}
		current = *c.ParentID
	}
	return false
}

// buildTree assembles a hierarchical view of the communities.
// Roots are communities whose parent_id is nil or points to a missing parent.
func buildTree(communities []model.Community) []model.HierarchicalCommunity {
	byID := make(map[string]model.Community, len(communities))
	childrenOf := make(map[string][]string, len(communities))
	var roots []string

	for _, c := range communities {
		byID[c.ID] = c
		if c.ParentID == nil {
			roots = append(roots, c.ID)
			continue
		}
		childrenOf[*c.ParentID] = append(childrenOf[*c.ParentID], c.ID)
	}

	var build func(id string, visited map[string]bool) model.HierarchicalCommunity
	build = func(id string, visited map[string]bool) model.HierarchicalCommunity {
		if visited[id] {
			return model.HierarchicalCommunity{ID: id}
		}
		visited[id] = true
		c := byID[id]
		hc := model.HierarchicalCommunity{
			ID:        c.ID,
			ParentID:  c.ParentID,
			Name:      c.Name,
			Color:     c.Color,
			Level:     c.Level,
			Domain:    c.Domain,
			NodeCount: c.NodeCount,
		}
		for _, childID := range childrenOf[id] {
			hc.Children = append(hc.Children, build(childID, visited))
		}
		return hc
	}

	result := make([]model.HierarchicalCommunity, 0, len(roots))
	for _, id := range roots {
		result = append(result, build(id, make(map[string]bool)))
	}
	return result
}
