package service

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"core/internal/model"
	"core/internal/repository"
)

// Sentinel errors returned by NodeService so handlers can map them to
// HTTP status codes.
var (
	ErrNodeNotFound  = errors.New("node not found")
	ErrNodeExists    = errors.New("node already exists")
	ErrNodeCommunity = errors.New("community does not exist")
)

// NodeService provides business logic for node operations.
//
// TimelineRange is cached in memory because computing it requires an
// O(N) Cypher aggregation over every Concept node. With many concurrent
// readers this would otherwise be re-scanned on every request. The
// cache is invalidated by every Create/Update/Delete that could change
// the result; the next read after an invalidation pays one recompute,
// subsequent reads are O(1).
type NodeService struct {
	repo     *repository.NodeRepository
	commRepo *repository.CommunityRepository

	timelineMu    sync.Mutex
	timelineCache *model.TimelineRange
}

// NewNodeService creates a new NodeService.
//
// The community repository is injected so the service can validate
// community_id values supplied in create/update requests before persisting
// them. It may be nil if the caller is sure no community validation is
// needed (e.g. in tests).
func NewNodeService(repo *repository.NodeRepository, commRepo *repository.CommunityRepository) *NodeService {
	return &NodeService{repo: repo, commRepo: commRepo}
}

// List returns paginated nodes.
func (s *NodeService) List(ctx context.Context, offset, limit int, search string) (*model.NodesListResponse, error) {
	var nodes []model.Node
	var total int
	var err error

	if search != "" {
		nodes, total, err = s.repo.Search(ctx, search, offset, limit)
	} else {
		nodes, total, err = s.repo.List(ctx, offset, limit)
	}
	if err != nil {
		return nil, err
	}

	return &model.NodesListResponse{
		Nodes: nodes,
		Pagination: model.Pagination{
			Offset:  offset,
			Limit:   limit,
			Total:   total,
			HasMore: offset+limit < total,
		},
	}, nil
}

// Get returns a node by ID.
func (s *NodeService) Get(ctx context.Context, id string) (*model.Node, error) {
	return s.repo.Get(ctx, id)
}

// Create creates a new node.
//
// If req.ID is empty a UUID is generated by the repository; the service
// then re-reads the node using the returned identifier. If
// req.CommunityID is non-nil, the service verifies that the referenced
// community exists before persisting the node.
func (s *NodeService) Create(ctx context.Context, req model.NodeCreateRequest) (*model.Node, error) {
	if req.ID != "" {
		exists, err := s.repo.Exists(ctx, req.ID)
		if err != nil {
			return nil, err
		}
		if exists {
			return nil, ErrNodeExists
		}
	}
	if err := s.validateCommunity(ctx, req.CommunityID); err != nil {
		return nil, err
	}
	id, err := s.repo.Create(ctx, req)
	if err != nil {
		return nil, err
	}
	// A new node may have introduced a year outside the cached range.
	s.invalidateTimelineRange()
	return s.repo.Get(ctx, id)
}

// Update updates an existing node.
//
// The CommunityID field is tri-state:
//   - nil  -> leave the assignment unchanged
//   - &nil -> remove the node from its community
//   - &int -> assign to the given community (validated below)
func (s *NodeService) Update(ctx context.Context, id string, req model.NodeUpdateRequest) (*model.Node, error) {
	if req.CommunityID != nil && *req.CommunityID != nil {
		if err := s.validateCommunity(ctx, *req.CommunityID); err != nil {
			return nil, err
		}
	}
	return s.repo.Update(ctx, id, req)
}

// Delete deletes a node by ID.
// Returns ErrNodeNotFound when the node does not exist.
func (s *NodeService) Delete(ctx context.Context, id string) error {
	existed, err := s.repo.Delete(ctx, id)
	if err != nil {
		return err
	}
	if !existed {
		return ErrNodeNotFound
	}
	return nil
}

// GetAll returns all nodes and edges in the graph.
func (s *NodeService) GetAll(ctx context.Context) ([]model.Node, []model.Edge, error) {
	return s.repo.GetAll(ctx)
}

// TimelineRange returns the [minYear, maxYear] span covered by every
// node's `first_appeared` field.
//
// The result is computed by the repository via an O(N) Cypher scan and
// cached in memory. Subsequent calls are O(1) until a Create, Update or
// Delete invalidates the cache. The cache protects the database from
// repeated scans when many concurrent readers hit the endpoint.
func (s *NodeService) TimelineRange(ctx context.Context) (model.TimelineRange, error) {
	s.timelineMu.Lock()
	if s.timelineCache != nil {
		cached := *s.timelineCache
		s.timelineMu.Unlock()
		return cached, nil
	}
	s.timelineMu.Unlock()

	tr, err := s.repo.TimelineRange(ctx)
	if err != nil {
		return model.TimelineRange{}, err
	}

	s.timelineMu.Lock()
	s.timelineCache = &tr
	s.timelineMu.Unlock()
	return tr, nil
}

// invalidateTimelineRange drops the cached range. Safe to call from
// write paths; the next TimelineRange call will recompute.
func (s *NodeService) invalidateTimelineRange() {
	s.timelineMu.Lock()
	s.timelineCache = nil
	s.timelineMu.Unlock()
}

// validateCommunity returns ErrNodeCommunity if the community does not
// exist. When the service is constructed without a community repository
// the check is skipped (caller responsibility).
func (s *NodeService) validateCommunity(ctx context.Context, id *string) error {
	if id == nil || s.commRepo == nil {
		return nil
	}
	exists, err := s.commRepo.Exists(ctx, *id)
	if err != nil {
		return fmt.Errorf("failed to validate community: %w", err)
	}
	if !exists {
		return ErrNodeCommunity
	}
	return nil
}
